name: Sync to Dropbox

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Dropbox
        uses: nwtgck/actions-dropbox@v2.0.0
        with:
          dropbox-token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          local-path: ./youtube_channels.m3u   # ✅ File is in repo root
          dropbox-path: /Apps/github_m3u/youtube_channels.m3u