name: Sync to Dropbox

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Dropbox
        uses: nwtgck/actions-dropbox@v2
        with:
          dropboxToken: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          arguments: upload ./MyM3UPlaylist/youtube_channels.m3u /dropbox/Apps/github_m3u
