name: Sync to Dropbox
on:
  push:
    branches:
      - main
    paths:
      - 'youtube_channels.m3u'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dropbox Uploader
        run: |
          curl -L -o dropbox_uploader.sh https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh
          chmod +x dropbox_uploader.sh

      - name: Configure Dropbox Uploader
        run: |
          echo "APP_KEY=${{ secrets.DROPBOX_APP_KEY }}" > ~/.dropbox_uploader
          echo "APP_SECRET=${{ secrets.DROPBOX_APP_SECRET }}" >> ~/.dropbox_uploader
          echo "ACCESS_TOKEN=${{ secrets.DROPBOX_ACCESS_TOKEN }}" >> ~/.dropbox_uploader
          echo "ACCESS_TOKEN_SECRET=${{ secrets.DROPBOX_ACCESS_TOKEN_SECRET }}" >> ~/.dropbox_uploader

      - name: Upload to Dropbox
        run: |
          if [ -f "./youtube_channels.m3u" ]; then
            ./dropbox_uploader.sh upload ./youtube_channels.m3u /github_m3u/youtube_channels.m3u
          else
            echo "File not found!"
            exit 1
          fi
